version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: photography-portfolio-db
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d portfolio"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: 