# Railway deployment configuration for Photography Portfolio
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Single service deployment serving both frontend and backend
[environments.production]
  [environments.production.variables]
    ENVIRONMENT = "production"
    PORT = "8080"
    TZ = "UTC"
    # Additional environment variables to be set in Railway dashboard:
    # JWT_SECRET (generate secure 32+ char string)
    # DATABASE_URL (automatically provided by Railway PostgreSQL)
    # STRIPE_SECRET_KEY (your Stripe secret key)
    # STRIPE_PUBLISHABLE_KEY (your Stripe publishable key)
    # STRIPE_WEBHOOK_SECRET (webhook endpoint secret)
    # CORS_ORIGIN (your Railway app URL) 